In [142]:
import torch
print(torch.__version__)

2.12.0+cu132


In [143]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
    
else:
    print("GPU not available. Using CPU")

GPU is available
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


In [144]:
# creating a tensor
a = torch.empty(2,3)
print(a)

tensor([[-2.6682e-23,  1.4055e-42,  0.0000e+00],
        [ 3.0547e+00,  0.0000e+00,  3.0156e+00]])


In [145]:
#check type
type(a)

torch.Tensor

In [146]:
#using zeros
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [147]:
#using ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [148]:
# using rand

torch.rand(3,3)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])

In [149]:
# use of seed same random values
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [150]:
torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ]
)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [151]:
#using arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [152]:
# line space
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [153]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [154]:
torch.full((3,3),7)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

### Tensor shapes

In [155]:
import torch.share


x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

x.shape

torch.Size([2, 3])

In [156]:
torch.empty_like(x)

tensor([[                  0, 4531178025744207146, 4563528883354732034],
        [4506409129725112152,          1052227146,                   1]])

In [157]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [158]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [159]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### tensor data types

In [160]:
x.dtype

torch.int64

In [161]:
torch.tensor([
    [1.0,2.0,3.0],
    [5.6,7,9]
], dtype=torch.int32)

tensor([[1, 2, 3],
        [5, 7, 9]], dtype=torch.int32)

In [162]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

In [163]:
# addition

x = torch.full((3,3),5)
x+2
# subtraction
x-3
#multiplication
x*3
# division
x//3
# int division


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [164]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [165]:
#add
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [166]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [167]:
a*b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [168]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [169]:
c = torch.tensor([1,-2,-3,5])


In [170]:
torch.abs(c)

tensor([1, 2, 3, 5])

In [171]:
torch.neg(c)

tensor([-1,  2,  3, -5])

In [172]:
d = torch.rand(1,5)
d

tensor([[0.4440, 0.9478, 0.7445, 0.4892, 0.2426]])

In [173]:
torch.round(d)

tensor([[0., 1., 1., 0., 0.]])

In [174]:
torch.ceil(d)

tensor([[1., 1., 1., 1., 1.]])

In [175]:
torch.floor(d)

tensor([[0., 0., 0., 0., 0.]])

In [176]:
torch.clamp(d, min=2, max=3)

tensor([[2., 2., 2., 2., 2.]])

### Reduction Operation

In [177]:
e=torch.randint(size=(3,3), low=5, high=20, dtype=torch.float32)
e

tensor([[15., 12., 10.],
        [ 5., 19., 10.],
        [17.,  8., 14.]])

In [178]:
# sum
torch.sum(e)

tensor(110.)

In [179]:
#sum along column
torch.sum(e, dim=0)

tensor([37., 39., 34.])

In [180]:
torch.mean(e)

tensor(12.2222)

In [181]:
torch.mean(e, dim=0)

tensor([12.3333, 13.0000, 11.3333])

In [182]:
torch.median(e)

tensor(12.)

In [183]:
torch.max(e)

tensor(19.)

In [184]:
torch.prod(e)

tensor(3.2558e+09)

In [185]:
torch.std(e)

tensor(4.4659)

In [186]:
torch.var(e)

tensor(19.9444)

In [187]:
torch.argmax(e)

tensor(4)

In [188]:
torch.argmin(e)

tensor(3)

### Matrix operations

In [189]:
torch.manual_seed(42)

f = torch.randint(size=(3,3), low=10, high=99, dtype=torch.float32)
g = torch.randint(size=(3,3), low=10, high=99, dtype=torch.float32)

print(f)
print(g)

tensor([[21., 75., 83.],
        [90., 13., 59.],
        [86., 64., 76.]])
tensor([[76., 11., 69.],
        [42., 24., 21.],
        [12., 98., 30.]])


In [190]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 5742., 10165.,  5514.],
        [ 8094.,  7084.,  8253.],
        [10136.,  9930.,  9558.]])

In [191]:
# dot product
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])
torch.dot(v1,v2)

tensor(11)

In [193]:
# transpose
torch.transpose(g,0,1) # row to column 

tensor([[76., 42., 12.],
        [11., 24., 98.],
        [69., 21., 30.]])

In [194]:
# determinant
torch.det(g)

tensor(151356.)

In [195]:
torch.inverse(g)

tensor([[-0.0088,  0.0425, -0.0094],
        [-0.0067,  0.0096,  0.0086],
        [ 0.0253, -0.0483,  0.0090]])

### Comparison Operations

In [196]:
# grater
f>g

tensor([[False,  True,  True],
        [ True, False,  True],
        [ True, False,  True]])