In [2]:
import torch
print(torch.__version__)

2.12.0+cu132


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
    
else:
    print("GPU not available. Using CPU")

GPU is available
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


In [4]:
# creating a tensor
a = torch.empty(2,3)
print(a)

tensor([[-7.1611e-15,  9.3747e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [5]:
#check type
type(a)

torch.Tensor

In [6]:
#using zeros
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand

torch.rand(3,3)

tensor([[0.4776, 0.6595, 0.6732],
        [0.2484, 0.3435, 0.3050],
        [0.3668, 0.5330, 0.6007]])

In [9]:
# use of seed same random values
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ]
)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
#using arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [12]:
# line space
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [13]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
torch.full((3,3),7)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

### Tensor shapes

In [15]:
import torch.share


x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[2876151892208,             0,             0],
        [            0,             0,             0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### tensor data types

In [20]:
x.dtype

torch.int64

In [21]:
torch.tensor([
    [1.0,2.0,3.0],
    [5.6,7,9]
], dtype=torch.int32)

tensor([[1, 2, 3],
        [5, 7, 9]], dtype=torch.int32)

In [22]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

In [23]:
# addition

x = torch.full((3,3),5)
x+2
# subtraction
x-3
#multiplication
x*3
# division
x//3
# int division


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [24]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [25]:
#add
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [26]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [27]:
a*b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [28]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [29]:
c = torch.tensor([1,-2,-3,5])


In [30]:
torch.abs(c)

tensor([1, 2, 3, 5])

In [31]:
torch.neg(c)

tensor([-1,  2,  3, -5])

In [32]:
d = torch.rand(1,5)
d

tensor([[0.4440, 0.9478, 0.7445, 0.4892, 0.2426]])

In [33]:
torch.round(d)

tensor([[0., 1., 1., 0., 0.]])

In [34]:
torch.ceil(d)

tensor([[1., 1., 1., 1., 1.]])

In [35]:
torch.floor(d)

tensor([[0., 0., 0., 0., 0.]])

In [36]:
torch.clamp(d, min=2, max=3)

tensor([[2., 2., 2., 2., 2.]])

### Reduction Operation

In [37]:
e=torch.randint(size=(3,3), low=5, high=20, dtype=torch.float32)
e

tensor([[15., 12., 10.],
        [ 5., 19., 10.],
        [17.,  8., 14.]])

In [38]:
# sum
torch.sum(e)

tensor(110.)

In [39]:
#sum along column
torch.sum(e, dim=0)

tensor([37., 39., 34.])

In [40]:
torch.mean(e)

tensor(12.2222)

In [41]:
torch.mean(e, dim=0)

tensor([12.3333, 13.0000, 11.3333])

In [42]:
torch.median(e)

tensor(12.)

In [43]:
torch.max(e)

tensor(19.)

In [44]:
torch.prod(e)

tensor(3.2558e+09)

In [45]:
torch.std(e)

tensor(4.4659)

In [46]:
torch.var(e)

tensor(19.9444)

In [47]:
torch.argmax(e)

tensor(4)

In [48]:
torch.argmin(e)

tensor(3)

### Matrix operations

In [49]:
torch.manual_seed(42)

f = torch.randint(size=(3,3), low=10, high=99, dtype=torch.float32)
g = torch.randint(size=(3,3), low=10, high=99, dtype=torch.float32)

print(f)
print(g)

tensor([[21., 75., 83.],
        [90., 13., 59.],
        [86., 64., 76.]])
tensor([[76., 11., 69.],
        [42., 24., 21.],
        [12., 98., 30.]])


In [50]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 5742., 10165.,  5514.],
        [ 8094.,  7084.,  8253.],
        [10136.,  9930.,  9558.]])

In [51]:
# dot product
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])
torch.dot(v1,v2)

tensor(11)

In [52]:
# transpose
torch.transpose(g,0,1) # row to column 

tensor([[76., 42., 12.],
        [11., 24., 98.],
        [69., 21., 30.]])

In [53]:
# determinant
torch.det(g)

tensor(151356.)

In [54]:
torch.inverse(g)

tensor([[-0.0088,  0.0425, -0.0094],
        [-0.0067,  0.0096,  0.0086],
        [ 0.0253, -0.0483,  0.0090]])

### Comparison Operations

In [55]:
# grater
f>g

tensor([[False,  True,  True],
        [ True, False,  True],
        [ True, False,  True]])

In [56]:
f < g

tensor([[ True, False, False],
        [False,  True, False],
        [False,  True, False]])

In [57]:
f == g

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

### Special Functions

In [58]:
k = torch.randint(size=(3,3), low=10, high=99, dtype=torch.float32)
k

tensor([[65., 70., 96.],
        [29., 20., 70.],
        [35., 75., 54.]])

In [59]:
torch.log(k)

tensor([[4.1744, 4.2485, 4.5643],
        [3.3673, 2.9957, 4.2485],
        [3.5553, 4.3175, 3.9890]])

In [60]:
torch.exp(k)

tensor([[1.6949e+28, 2.5154e+30,        inf],
        [3.9313e+12, 4.8517e+08, 2.5154e+30],
        [1.5860e+15, 3.7332e+32, 2.8308e+23]])

In [61]:
torch.sqrt(k)

tensor([[8.0623, 8.3666, 9.7980],
        [5.3852, 4.4721, 8.3666],
        [5.9161, 8.6603, 7.3485]])

In [62]:
torch.sigmoid(k)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [63]:
torch.softmax(k, dim=0)

tensor([[1.0000e+00, 6.6929e-03, 1.0000e+00],
        [2.3195e-16, 1.2909e-24, 5.1091e-12],
        [9.3576e-14, 9.9331e-01, 5.7495e-19]])

In [64]:
torch.relu(k)

tensor([[65., 70., 96.],
        [29., 20., 70.],
        [35., 75., 54.]])