In [116]:
import torch
print(torch.__version__)

2.12.0+cu132


In [117]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
    
else:
    print("GPU not available. Using CPU")

GPU is available
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


In [118]:
# creating a tensor
a = torch.empty(2,3)
print(a)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7565]])


In [119]:
#check type
type(a)

torch.Tensor

In [120]:
#using zeros
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [121]:
#using ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [122]:
# using rand

torch.rand(3,3)

tensor([[0.0134, 0.9002, 0.3916],
        [0.4598, 0.1849, 0.5973],
        [0.3511, 0.3857, 0.7167]])

In [123]:
# use of seed same random values
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [124]:
torch.tensor(
    [
        [1,2,3],
        [4,5,6]
    ]
)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [125]:
#using arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [126]:
# line space
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [127]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [128]:
torch.full((3,3),7)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

### Tensor shapes

In [129]:
import torch.share


x = torch.tensor([
    [1,2,3],
    [4,5,6]
])

x.shape

torch.Size([2, 3])

In [130]:
torch.empty_like(x)

tensor([[4535895798213452620, 4517408008396342592, 4511046036572008302],
        [4530798488084236116,          1058432783,                   1]])

In [131]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [132]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [133]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

### tensor data types

In [134]:
x.dtype

torch.int64

In [135]:
torch.tensor([
    [1.0,2.0,3.0],
    [5.6,7,9]
], dtype=torch.int32)

tensor([[1, 2, 3],
        [5, 7, 9]], dtype=torch.int32)

In [136]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### Mathematical Operations

In [137]:
# addition

x = torch.full((3,3),5)
x+2
# subtraction
x-3
#multiplication
x*3
# division
x//3
# int division


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [138]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [139]:
#add
a+b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [140]:
a-b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [141]:
a*b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [142]:
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [143]:
c = torch.tensor([1,-2,-3,5])


In [144]:
torch.abs(c)

tensor([1, 2, 3, 5])

In [145]:
torch.neg(c)

tensor([-1,  2,  3, -5])

In [146]:
d = torch.rand(1,5)
d

tensor([[0.4440, 0.9478, 0.7445, 0.4892, 0.2426]])

In [147]:
torch.round(d)

tensor([[0., 1., 1., 0., 0.]])

In [148]:
torch.ceil(d)

tensor([[1., 1., 1., 1., 1.]])

In [149]:
torch.floor(d)

tensor([[0., 0., 0., 0., 0.]])

In [150]:
torch.clamp(d, min=2, max=3)

tensor([[2., 2., 2., 2., 2.]])

### Reduction Operation

In [151]:
e=torch.randint(size=(3,3), low=5, high=20, dtype=torch.float32)
e

tensor([[15., 12., 10.],
        [ 5., 19., 10.],
        [17.,  8., 14.]])

In [152]:
# sum
torch.sum(e)

tensor(110.)

In [153]:
#sum along column
torch.sum(e, dim=0)

tensor([37., 39., 34.])

In [154]:
torch.mean(e)

tensor(12.2222)

In [155]:
torch.mean(e, dim=0)

tensor([12.3333, 13.0000, 11.3333])

In [156]:
torch.median(e)

tensor(12.)

In [157]:
torch.max(e)

tensor(19.)

In [158]:
torch.prod(e)

tensor(3.2558e+09)

In [159]:
torch.std(e)

tensor(4.4659)

In [160]:
torch.var(e)

tensor(19.9444)

In [161]:
torch.argmax(e)

tensor(4)

In [162]:
torch.argmin(e)

tensor(3)

### Matrix operations

In [163]:
torch.manual_seed(42)

f = torch.randint(size=(3,3), low=10, high=99, dtype=torch.float32)
g = torch.randint(size=(3,3), low=10, high=99, dtype=torch.float32)

print(f)
print(g)

tensor([[21., 75., 83.],
        [90., 13., 59.],
        [86., 64., 76.]])
tensor([[76., 11., 69.],
        [42., 24., 21.],
        [12., 98., 30.]])


In [164]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 5742., 10165.,  5514.],
        [ 8094.,  7084.,  8253.],
        [10136.,  9930.,  9558.]])

In [165]:
# dot product
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])
torch.dot(v1,v2)

tensor(11)

In [166]:
# transpose
torch.transpose(g,0,1) # row to column 

tensor([[76., 42., 12.],
        [11., 24., 98.],
        [69., 21., 30.]])

In [167]:
# determinant
torch.det(g)

tensor(151356.)

In [168]:
torch.inverse(g)

tensor([[-0.0088,  0.0425, -0.0094],
        [-0.0067,  0.0096,  0.0086],
        [ 0.0253, -0.0483,  0.0090]])

### Comparison Operations

In [169]:
# grater
f>g

tensor([[False,  True,  True],
        [ True, False,  True],
        [ True, False,  True]])

In [170]:
f < g

tensor([[ True, False, False],
        [False,  True, False],
        [False,  True, False]])

In [171]:
f == g

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

### Special Functions

In [172]:
k = torch.randint(size=(3,3), low=10, high=99, dtype=torch.float32)
k

tensor([[65., 70., 96.],
        [29., 20., 70.],
        [35., 75., 54.]])

In [173]:
torch.log(k)

tensor([[4.1744, 4.2485, 4.5643],
        [3.3673, 2.9957, 4.2485],
        [3.5553, 4.3175, 3.9890]])

In [174]:
torch.exp(k)

tensor([[1.6949e+28, 2.5154e+30,        inf],
        [3.9313e+12, 4.8517e+08, 2.5154e+30],
        [1.5860e+15, 3.7332e+32, 2.8308e+23]])

In [175]:
torch.sqrt(k)

tensor([[8.0623, 8.3666, 9.7980],
        [5.3852, 4.4721, 8.3666],
        [5.9161, 8.6603, 7.3485]])

In [176]:
torch.sigmoid(k)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [177]:
torch.softmax(k, dim=0)

tensor([[1.0000e+00, 6.6929e-03, 1.0000e+00],
        [2.3195e-16, 1.2909e-24, 5.1091e-12],
        [9.3576e-14, 9.9331e-01, 5.7495e-19]])

In [178]:
torch.relu(k)

tensor([[65., 70., 96.],
        [29., 20., 70.],
        [35., 75., 54.]])

### Inplace Operations

In [179]:
m = torch.rand(2,2)
n = torch.rand(2,2)

In [180]:
m.add_(n)

tensor([[0.2746, 1.4332],
        [0.5894, 1.2892]])

In [181]:
m

tensor([[0.2746, 1.4332],
        [0.5894, 1.2892]])

In [182]:
m.relu_()

tensor([[0.2746, 1.4332],
        [0.5894, 1.2892]])

In [183]:
m

tensor([[0.2746, 1.4332],
        [0.5894, 1.2892]])

### Copying a tensor

In [184]:
a = torch.rand(3,3)
a

tensor([[0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343],
        [0.3644, 0.7104, 0.9464]])

In [185]:
b = a.clone()

In [186]:
b

tensor([[0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343],
        [0.3644, 0.7104, 0.9464]])

In [187]:
a[0][0] = 10
a

tensor([[10.0000,  0.5779,  0.9040],
        [ 0.5547,  0.3423,  0.6343],
        [ 0.3644,  0.7104,  0.9464]])

In [188]:
b

tensor([[0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343],
        [0.3644, 0.7104, 0.9464]])

In [189]:
print(id(a))
print(id(b))

1761945441760
1761683723504


### tensor operation in gpu

In [190]:
torch.cuda.is_available()

True

In [191]:
device = torch.device('cuda')
print(device)

cuda


In [192]:
# create a tensor on gpu vram

torch.rand((2,3), device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [193]:
# moving an existing tensor to gpu
a

tensor([[10.0000,  0.5779,  0.9040],
        [ 0.5547,  0.3423,  0.6343],
        [ 0.3644,  0.7104,  0.9464]])

In [194]:
b = a.to(device)
b

tensor([[10.0000,  0.5779,  0.9040],
        [ 0.5547,  0.3423,  0.6343],
        [ 0.3644,  0.7104,  0.9464]], device='cuda:0')

In [195]:
b + 5

tensor([[15.0000,  5.5779,  5.9040],
        [ 5.5547,  5.3423,  5.6343],
        [ 5.3644,  5.7104,  5.9464]], device='cuda:0')

### GPU tensors vs CPU Tensors

In [196]:
import time

size = 10000

matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

# measure time on CPU
start_time = time.time()
result = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time() - start_time
print(f"Time on cpu: {cpu_time:.4f} seconds")


# move matrices to gpu
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu1.to('cuda')

# measure time on GPU
start_time = time.time()
result = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time
print(f"Time on GPU: {gpu_time:.4f} seconds")

#comparison
print("Speedup (CPU/GPU): ", cpu_time/gpu_time)

Time on cpu: 3.2986 seconds
Time on GPU: 0.3405 seconds
Speedup (CPU/GPU):  9.686301676759898


### reshaping tensors

In [197]:
a = torch.rand(4,4)
a

tensor([[0.3499, 0.4741, 0.1211, 0.3458],
        [0.8083, 0.3017, 0.6378, 0.4387],
        [0.5875, 0.2907, 0.2837, 0.8993],
        [0.6628, 0.1727, 0.2775, 0.2066]])

In [198]:
# reshape
a.reshape(2,2,2,2) # multiplication should be same size of the orginal dimentions multiplications 4x4 = 16, 2x2x2x2 = 16

tensor([[[[0.3499, 0.4741],
          [0.1211, 0.3458]],

         [[0.8083, 0.3017],
          [0.6378, 0.4387]]],


        [[[0.5875, 0.2907],
          [0.2837, 0.8993]],

         [[0.6628, 0.1727],
          [0.2775, 0.2066]]]])

In [199]:
#flatten
a.flatten()

tensor([0.3499, 0.4741, 0.1211, 0.3458, 0.8083, 0.3017, 0.6378, 0.4387, 0.5875,
        0.2907, 0.2837, 0.8993, 0.6628, 0.1727, 0.2775, 0.2066])

In [200]:
# permute
b = torch.rand(2,3,4)
b

tensor([[[0.0025, 0.4246, 0.0147, 0.6856],
         [0.5290, 0.2430, 0.8495, 0.0092],
         [0.2848, 0.0483, 0.2704, 0.7201]],

        [[0.6314, 0.7832, 0.5447, 0.5934],
         [0.8648, 0.7149, 0.3839, 0.0214],
         [0.3823, 0.2968, 0.6859, 0.7515]]])

In [201]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [202]:
# unsquezze
c = torch.rand(226,226,3) # a normal rgb image
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [203]:
# squzze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

### Numpy and Pytorch

In [204]:
import numpy as np

In [205]:
a = torch.tensor([
    1,2,3
])

a

tensor([1, 2, 3])

In [206]:
b = a.numpy()

In [207]:
b

array([1, 2, 3])

In [208]:
type(b)

numpy.ndarray

In [209]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [214]:
d = torch.from_numpy(c)
type(d)

torch.Tensor

In [215]:
type(d)

torch.Tensor